name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10.16.3', '12.19.1']
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        sed -i "s/\$NODE_VERSION/$NODE_VERSION/" Dockerfile
        BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/refs\/tags\///g")
        TAG="node-$NODE_VERSION"
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
        [[ "$BRANCH" != "master" ]] && TAG="$TAG-$BRANCH"
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$TAG .
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$TAG
      env:
        DOCKER_REGISTRY: registry.hub.docker.com
        DOCKER_REPOSITORY: blowltd
        DOCKER_IMAGE: docker-ci
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        NODE_VERSION: ${{ matrix.node }}
