name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['8.10', '10.16.3']
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: |
        sed -i "s/\$NODE_VERSION/$NODE_VERSION/" Dockerfile
        BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/refs\/tags\///g")
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
        docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$BRANCH .
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$BRANCH
        [[ "$BRANCH" == "master" ]] || exit 0;
        docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$BRANCH $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:latest
        docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$DOCKER_IMAGE:latest
      env:
        #DOCKER_REGISTRY: docker.pkg.github.com
        #DOCKER_REPOSITORY: ${{ github.repository }}
        DOCKER_REGISTRY: registry.hub.docker.com
        DOCKER_REPOSITORY: blowltd
        DOCKER_IMAGE: docker-ci
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        NODE_VERSION: ${{ matrix.node }}